site_name: PróSiga Docs
site_description: Documentação do sistema de gerenciamento acadêmico PróSiga
repo_url: https://github.com/ProSiga-organization/prosiga-docs
repo_name: prosiga-docs

# Estilo inspirado no exemplo anterior (Material + features modernas), sem estrutura pesada.
theme:
  name: material
  language: pt
  features:
    - navigation.top
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.instant
    - navigation.path
    - toc.integrate
    - search.suggest
    - search.highlight
    - toc.follow
    - content.code.copy
    - content.code.annotation
    - content.tooltips
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      toggle:
        icon: material/brightness-7
        name: Modo escuro
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/brightness-4
        name: Modo claro
  logo: assets/logo.png
  favicon: assets/logo.png

extra_css:
  - assets/styles/extra.css
extra_javascript:
  - assets/scripts/mathjax.js
  - https://unpkg.com/mathjax@3/es5/tex-mml-chtml.js

markdown_extensions:
  - admonition
  - attr_list
  - def_list
  - tables
  - footnotes
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.highlight:
      anchor_linenums: true
      linenums: true
      line_spans: __span
      pygments_lang_class: true
      use_pygments: true
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.tasklist:
      custom_checkbox: true
  - toc:
      permalink: true

nav:
  - Início: index.md
  - Backlog: backlog.md
  - Diagrama de Classes: diagrama.md
